/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sH5mUUJuFeN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function Main() {
  return (
    <>
      <header className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between">
        <div className="flex items-center">
          <CatIcon className="h-8 w-8 mr-2" />
          <h1 className="text-2xl font-bold">Hackernews for Cats</h1>
        </div>
        <div className="flex items-center">
          <div className="relative w-64 mr-4">
            <Input
              className="bg-gray-800 text-white px-4 py-2 rounded-md w-full"
              placeholder="Search cat news..."
              type="search"
            />
            <SearchIcon className="absolute right-2 top-2 h-4 w-4 text-gray-400" />
          </div>
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link className="hover:text-gray-400" href="#">
                  Top
                </Link>
              </li>
              <li>
                <Link className="hover:text-gray-400" href="#">
                  New
                </Link>
              </li>
              <li>
                <Link className="hover:text-gray-400" href="#">
                  Comments
                </Link>
              </li>
              <li>
                <Link className="hover:text-gray-400" href="#">
                  Submit
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <div className="grid grid-cols-12 gap-6 p-6">
        <div className="col-span-8">
          <div className="space-y-6">
            <div className="bg-white rounded-md shadow-md p-4">
              <h2 className="text-xl font-bold mb-2">
                <Link className="hover:text-gray-600" href="#">
                  Catnip Discovered to Have Psychoactive Effects on Felines
                </Link>
              </h2>
              <p className="text-gray-600 mb-2">
                A new study has found that catnip, the aromatic herb that drives cats wild, has psychoactive effects on
                felines. Researchers discovered that the active compound in catnip, nepetalactone, binds to the same
                receptors in the brain as THC, the main psychoactive compound in cannabis.
              </p>
              <Link className="text-blue-500 hover:text-blue-600" href="#">
                Read more
              </Link>
            </div>
            <div className="bg-white rounded-md shadow-md p-4">
              <h2 className="text-xl font-bold mb-2">
                <Link className="hover:text-gray-600" href="#">
                  Cats Discover Keyboard Shortcuts, Immediately Become More Productive
                </Link>
              </h2>
              <p className="text-gray-600 mb-2">
                In a surprising turn of events, cats across the world have discovered the power of keyboard shortcuts,
                leading to a significant increase in their productivity. Feline experts believe this newfound ability to
                quickly navigate their digital environments will revolutionize the way cats work and play.
              </p>
              <Link className="text-blue-500 hover:text-blue-600" href="#">
                Read more
              </Link>
            </div>
            <div className="bg-white rounded-md shadow-md p-4">
              <h2 className="text-xl font-bold mb-2">
                <Link className="hover:text-gray-600" href="#">
                  Cats Invent Purr-fect Coding Language, Revolutionize Software Development
                </Link>
              </h2>
              <p className="text-gray-600 mb-2">
                In a groundbreaking development, cats have created their own coding language, dubbed "Meowscript," that
                is taking the software development world by storm. Feline programmers claim that Meowscript is not only
                more efficient than traditional programming languages, but also more expressive, allowing them to
                communicate their feline needs and desires directly to the computer.
              </p>
              <Link className="text-blue-500 hover:text-blue-600" href="#">
                Read more
              </Link>
            </div>
          </div>
        </div>
        <div className="col-span-4">
          <div className="bg-white rounded-md shadow-md p-4 mb-6">
            <h3 className="text-lg font-bold mb-2">Popular Tags</h3>
            <div className="flex flex-wrap gap-2">
              <Badge className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50" variant="secondary">
                <Link href="#">Catnip</Link>
              </Badge>
              <Badge className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50" variant="secondary">
                <Link href="#">Cats</Link>
              </Badge>
              <Badge className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50" variant="secondary">
                <Link href="#">Productivity</Link>
              </Badge>
              <Badge className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50" variant="secondary">
                <Link href="#">Coding</Link>
              </Badge>
              <Badge className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50" variant="secondary">
                <Link href="#">Software</Link>
              </Badge>
            </div>
          </div>
          <div className="bg-white rounded-md shadow-md p-4">
            <h3 className="text-lg font-bold mb-2">Top Contributors</h3>
            <ul className="space-y-2">
              <li className="flex items-center">
                <Avatar className="w-8 h-8 mr-2">
                  <AvatarImage alt="@catmaster" src="/placeholder-user.jpg" />
                  <AvatarFallback>CM</AvatarFallback>
                </Avatar>
                <div>
                  <Link className="font-medium hover:text-gray-600" href="#">
                    @catmaster
                  </Link>
                  <p className="text-gray-600 text-sm">1,234 points</p>
                </div>
              </li>
              <li className="flex items-center">
                <Avatar className="w-8 h-8 mr-2">
                  <AvatarImage alt="@kittycat" src="/placeholder-user.jpg" />
                  <AvatarFallback>KC</AvatarFallback>
                </Avatar>
                <div>
                  <Link className="font-medium hover:text-gray-600" href="#">
                    @kittycat
                  </Link>
                  <p className="text-gray-600 text-sm">987 points</p>
                </div>
              </li>
              <li className="flex items-center">
                <Avatar className="w-8 h-8 mr-2">
                  <AvatarImage alt="@meowmeow" src="/placeholder-user.jpg" />
                  <AvatarFallback>MM</AvatarFallback>
                </Avatar>
                <div>
                  <Link className="font-medium hover:text-gray-600" href="#">
                    @meowmeow
                  </Link>
                  <p className="text-gray-600 text-sm">789 points</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </>
  )
}

function CatIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 5c.67 0 1.35.09 2 .26 1.78-2 5.03-2.84 6.42-2.26 1.4.58-.42 7-.42 7 .57 1.07 1 2.24 1 3.44C21 17.9 16.97 21 12 21s-9-3-9-7.56c0-1.25.5-2.4 1-3.44 0 0-1.89-6.42-.5-7 1.39-.58 4.72.23 6.5 2.23A9.04 9.04 0 0 1 12 5Z" />
      <path d="M8 14v.5" />
      <path d="M16 14v.5" />
      <path d="M11.25 16.25h1.5L12 17l-.75-.75Z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
